var faker = require('faker');
console.log("LISTA DE PRODUTOS ALEATÓRIOS:\n");
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
faker.locale = "pt_BR";
console.log("\nLISTA DE PRODUTOS ALEATÓRIOS:\n");
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));
console.log(faker.fake("{{commerce.productName}}-> R${{commerce.price}}"));